
###

GET http://localhost:8080/contacts 
####
GET http://localhost:8080/contacts/626dfffdc29ea86894009ac3
###
GET http://localhost:8080/contacts/626dfffdc29ea86894009ac4
###
GET http://localhost:8080/contacts/626dfffdc29ea86894009ac5

// PRODUCTION Deploy 


### 
GET https://cs341week2.herokuapp.com/contacts 
